Simbionisme/percobaan/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_todo', add_todo, name='add_todo'),
	url(r'^fpb', fpb, name='fpb'),
	url(r'^lsb', lsb, name='lsb'),
	url(r'^insert_pendaftar', insert_pendaftar, name='insert_pendaftar'),
	url(r'^get_table', get_table, name='get_table'),
	url(r'^delete_todo/(?P<id>\d+)/$', delete_todo, name='delete_todo'),
	url(r'^open_pendaftar/(?P<no_u>\d+)/(?P<kode>\d+)/$', open_pendaftar, name='open_pendaftar'),

	
]

Simbionisme/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import login.urls as account
from login.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include(account, namespace='account')),
    url(r'^percobaan/', include(percobaan, namespace='percobaan')),
    url(r'^$', home, name='home'),
]

login/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^login/', indexLogin, name='login'),
    url(r'^submit-login', login, name='submitLogin'),
    url(r'^logout/', logout, name='logout'),
    url(r'^register/', register, name='register'),
    url(r'^submit-mahasiswa', submit_mahasiswa, name='submit-mahasiswa'),
    url(r'^submit-donatur-individu', submit_individual_donor, name='submit-donatur-individual'),
    url(r'^submit-donatur-yayasan', submit_yayasan, name='submit-donatur-yayasan'),
]

percobaan/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_todo', add_todo, name='add_todo'),
	url(r'^fpb', fpb, name='fpb'),
	url(r'^lsb', lsb, name='lsb'),
	url(r'^insert_pendaftar', insert_pendaftar, name='insert_pendaftar'),
	url(r'^get_table', get_table, name='get_table'),
	url(r'^delete_todo/(?P<id>\d+)/$', delete_todo, name='delete_todo'),
	url(r'^open_pendaftar/(?P<no_u>\d+)/(?P<kode>\d+)/$', open_pendaftar, name='open_pendaftar'),

	
]

Simbionisme/percobaan/forms.py
from django import forms
from django.forms import ModelForm
from .models import *
from django.db import connection

class Todo_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    title_attrs = {
        'type': 'text',
        'class': 'todo-form-input',
        'placeholder':'Masukan judul...'
    }
    description_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'Masukan deskripsi...'
    }

    title = forms.CharField(label='', required=True, max_length=27, widget=forms.TextInput(attrs=title_attrs))
    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

# cursor = connection.cursor()
# list_tabel = cursor.execute("select nama from")

class SB_Form(forms.Form):
    cursor = connection.cursor()
    query = "select kode_skema_beasiswa, kode_skema_beasiswa from skema_beasiswa_aktif where status= '%s' order by kode_skema_beasiswa ASC" % "aktif"
    cursor.execute(query)
    row = cursor.fetchall()

    print(row)
    
    # int masukankode = int(row[0][0])
    str masukannpm = '1606831224'
    str masukanemail = 'mahasin.anas@gmail.com'

    kode_beasiswa = forms.CharField(label='Kode Beasiswa', required=True, max_length=27, widget=forms.Select(choices=row, attrs={'class': 'btn btn-primary dropdown-toggle w-100'}))
    npm = forms.CharField(label='NPM', required=True, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter NPM'}, value=masukannpm))
    email = forms.CharField(label='Email', required=True, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter Email'}, value=masukanemail))
    ips = forms.CharField(label='Indeks Prestasi Semester', required=True, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'IPS'}))

    # class Meta:
    #     nama_attrs = {
    #         'type': 'text',
    #         'class': 'col-sm-12',
    #         'placeholder':'Masukan judul...'
    #     }
    #     description_attrs = {
    #         'type': 'text',
    #         'cols': 50,
    #         'rows': 4,
    #         'class': 'form-input',
    #         'id': 'inlineFormInput',
    #         'placeholder':'Masukan deskripsi...'
    #     }

    #     skema_attrs = {
    #         'class': 'col-sm-12',
    #     }

    #     model = SkemaBeasiswa, 
    #     fields = ['skema', 'judul', 'description']
    #     widgets = {
    #         'name': forms.TextInput(attrs=nama_attrs),
    #         'description': forms.Textarea(attrs=description_attrs),
    #         'skema' : forms.Select(attrs=skema_attrs),
    #     }

percobaan/forms.py
from django import forms
from django.forms import ModelForm
from .models import *
from django.db import connection

class Todo_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    title_attrs = {
        'type': 'text',
        'class': 'todo-form-input',
        'placeholder':'Masukan judul...'
    }
    description_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'Masukan deskripsi...'
    }

    title = forms.CharField(label='', required=True, max_length=27, widget=forms.TextInput(attrs=title_attrs))
    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

# cursor = connection.cursor()
# list_tabel = cursor.execute("select nama from")

class SB_Form(forms.Form):
    cursor = connection.cursor()
    query = "select kode_skema_beasiswa, kode_skema_beasiswa from skema_beasiswa_aktif where status= '%s' order by kode_skema_beasiswa ASC" % "aktif"
    cursor.execute(query)
    row = cursor.fetchall()

    print(row)
    
    # int masukankode = int(row[0][0])
    # str masukannpm = '1606831224'
    # str masukanemail = 'mahasin.anas@gmail.com'

    kode_beasiswa = forms.CharField(label='Kode Beasiswa', required=True, max_length=27, widget=forms.Select(choices=row, attrs={'class': 'btn btn-primary dropdown-toggle w-100'}))
    npm = forms.CharField(label='NPM', required=True, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter NPM'}))
    email = forms.CharField(label='Email', required=True, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter Email'}))
    ips = forms.CharField(label='Indeks Prestasi Semester', required=True, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'IPS'}))

    # class Meta:
    #     nama_attrs = {
    #         'type': 'text',
    #         'class': 'col-sm-12',
    #         'placeholder':'Masukan judul...'
    #     }
    #     description_attrs = {
    #         'type': 'text',
    #         'cols': 50,
    #         'rows': 4,
    #         'class': 'form-input',
    #         'id': 'inlineFormInput',
    #         'placeholder':'Masukan deskripsi...'
    #     }

    #     skema_attrs = {
    #         'class': 'col-sm-12',
    #     }

    #     model = SkemaBeasiswa, 
    #     fields = ['skema', 'judul', 'description']
    #     widgets = {
    #         'name': forms.TextInput(attrs=nama_attrs),
    #         'description': forms.Textarea(attrs=description_attrs),
    #         'skema' : forms.Select(attrs=skema_attrs),
    #     }

Simbionisme/percobaan/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import *
from .forms import *
from django.views.generic.base import RedirectView
from django.db import connection
from django.core import serializers
import datetime

# Create your views here.
response = {}
def index(request): 
	cursor = connection.cursor()
	sb = cursor.execute("select * from skema_beasiswa")
	response['sb'] = sb
	sb_form = SB_Form()
	response['sb_form'] = sb_form
	html = 'percobaan/fpb.html'
	cursor = connection.cursor()
	query = "select kode_skema_beasiswa, no_urut, tgl_tutup_pendaftaran, status, jumlah_pendaftar from skema_beasiswa_aktif"
	cursor.execute(query)
	sba_table = cursor.fetchall()

	return render(request, html, response)

def fpb(request):
	html = 'percobaan/fpb.html'
	return render(request, html, response)

def lsb(request):
	cursor = connection.cursor()
	query = "select no_urut, kode_skema_beasiswa, tgl_tutup_pendaftaran, status, jumlah_pendaftar from skema_beasiswa_aktif"
	cursor.execute(query)
	tabel_skema = cursor.fetchall()
	response['tabel_skema'] = tabel_skema
	html = 'percobaan/lsb.html'
	return render(request, html, response)

def open_pendaftar(request, no_u, kode):
	cursor = connection.cursor()
	query = "select no_urut, nama, npm, waktu_daftar, status_terima from pendaftaran natural join mahasiswa where no_urut= %s AND kode_skema_beasiswa = %s" % (no_u,kode)
	cursor.execute(query)
	pendaftaran = cursor.fetchall()
	response['tabel_pendaftaran'] = pendaftaran
	html = 'percobaan/lpsb.html'
	return render(request, html, response)

def add_todo(request):
	form = Todo_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['title'] = request.POST['title']
		response['description'] = request.POST['description']
		todo = Todo(title=response['title'],description=response['description'])
		todo.save()
		return HttpResponseRedirect('/percobaan/')
	else:
		return HttpResponseRedirect('/percobaan/')

def delete_todo(request, id):
	sb_delete = sb.objects.get(id=id)
	sb_delete.delete()

	return HttpResponseRedirect('/percobaan/')

def get_table(request):
	cursor = connection.cursor()
	query = "select no_urut ,kode_skema_beasiswa, tgl_tutup_pendaftaran, status, jumlah_pendaftar from skema_beasiswa_aktif"
	cursor.execute(query)
	sba_table = cursor.fetchall()
	data = serializers.serialize('json', sba_table)
	print(data)
	return HttpResponse(data)

def insert_pendaftar(request):
	form = SB_Form(request.POST or None)
	if (request.method == 'POST' and form.is_valid()):
		kode_beasiswa = request.POST['kode_beasiswa']
		NPM = request.POST['npm']
		email = request.POST['email']
		ips = request.POST['ips']
		time = datetime.datetime.now()
		time_real = '{:%Y-%m-%d %H:%M:%S}'.format(time)

		cursor = connection.cursor()
		count_query = "select no_urut from skema_beasiswa_aktif where kode_skema_beasiswa = %s" % kode_beasiswa
		cursor.execute(count_query)
		nobar_pendaftaran = int(cursor.fetchall()[0][0])

		print(nobar_pendaftaran)

		query = "insert into pendaftaran values (%s, %s, '%s', '%s', '%s', '%s')" % (nobar_pendaftaran, kode_beasiswa, NPM, time_real, 'aktif', '-')
		cursor.execute(query)


		cursor = connection.cursor()
		count_query = "select count(*) from pendaftaran"
		cursor.execute(count_query)
		nobar_pendaftaran = int(cursor.fetchall()[0][0])

		print()
		print(nobar_pendaftaran)
		print()
		print()

		return HttpResponseRedirect('/percobaan/')

percobaan/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import *
from .forms import *
from django.views.generic.base import RedirectView
from django.db import connection
from django.core import serializers
import datetime

# Create your views here.
response = {}
def index(request): 
	cursor = connection.cursor()
	sb = cursor.execute("select * from skema_beasiswa")
	response['sb'] = sb
	sb_form = SB_Form()
	response['sb_form'] = sb_form
	html = 'percobaan/fpb.html'
	cursor = connection.cursor()
	query = "select kode_skema_beasiswa, no_urut, tgl_tutup_pendaftaran, status, jumlah_pendaftar from skema_beasiswa_aktif"
	cursor.execute(query)
	sba_table = cursor.fetchall()

	return render(request, html, response)

def fpb(request):
	html = 'percobaan/fpb.html'
	return render(request, html, response)

def lsb(request):
	cursor = connection.cursor()
	query = "select no_urut, kode_skema_beasiswa, tgl_tutup_pendaftaran, status, jumlah_pendaftar from skema_beasiswa_aktif"
	cursor.execute(query)
	tabel_skema = cursor.fetchall()
	response['tabel_skema'] = tabel_skema
	html = 'percobaan/lsb.html'
	return render(request, html, response)

def open_pendaftar(request, no_u, kode):
	cursor = connection.cursor()
	query = "select no_urut, nama, npm, waktu_daftar, status_terima from pendaftaran natural join mahasiswa where no_urut= %s AND kode_skema_beasiswa = %s" % (no_u,kode)
	cursor.execute(query)
	pendaftaran = cursor.fetchall()
	response['tabel_pendaftaran'] = pendaftaran
	html = 'percobaan/lpsb.html'
	return render(request, html, response)

def add_todo(request):
	form = Todo_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['title'] = request.POST['title']
		response['description'] = request.POST['description']
		todo = Todo(title=response['title'],description=response['description'])
		todo.save()
		return HttpResponseRedirect('/percobaan/')
	else:
		return HttpResponseRedirect('/percobaan/')

def delete_todo(request, id):
	sb_delete = sb.objects.get(id=id)
	sb_delete.delete()

	return HttpResponseRedirect('/percobaan/')

def get_table(request):
	cursor = connection.cursor()
	query = "select no_urut ,kode_skema_beasiswa, tgl_tutup_pendaftaran, status, jumlah_pendaftar from skema_beasiswa_aktif"
	cursor.execute(query)
	sba_table = cursor.fetchall()
	data = serializers.serialize('json', sba_table)
	print(data)
	return HttpResponse(data)

def insert_pendaftar(request):
	form = SB_Form(request.POST or None)
	if (request.method == 'POST' and form.is_valid()):
		kode_beasiswa = request.POST['kode_beasiswa']
		NPM = request.POST['npm']
		email = request.POST['email']
		ips = request.POST['ips']
		time = datetime.datetime.now()
		time_real = '{:%Y-%m-%d %H:%M:%S}'.format(time)

		cursor = connection.cursor()
		count_query = "select no_urut from skema_beasiswa_aktif where kode_skema_beasiswa = %s" % kode_beasiswa
		cursor.execute(count_query)
		nobar_pendaftaran = int(cursor.fetchall()[0][0])

		print(nobar_pendaftaran)

		query = "insert into pendaftaran values (%s, %s, '%s', '%s', '%s', '%s')" % (nobar_pendaftaran, kode_beasiswa, NPM, time_real, 'aktif', '-')
		cursor.execute(query)


		cursor = connection.cursor()
		count_query = "select count(*) from pendaftaran"
		cursor.execute(count_query)
		nobar_pendaftaran = int(cursor.fetchall()[0][0])

		print()
		print(nobar_pendaftaran)
		print()
		print()

		return HttpResponseRedirect('/percobaan/')

percobaan/templates/percobaan/fpb.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static 'css/theme.css' %}" type="text/css"> </head>

<body class="">
  <div class="m-0 py-4 bg-primary">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="text-center">FORM PENDAFTARAN BEASISWA</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
      <h2></h2>
  </div>
  <div class="py-4">
      <div class="container">
          <div class="col-md-12 border p-4">
            <form id="form" method="POST" action="{% url 'percobaan:insert_pendaftar' %}">
                {% csrf_token %}
                {% for field in sb_form %}
                  <div class="form-group">
                    {{field.label_tag}}
                    {{field}}
                  </div>
                {% endfor %}
                <input id="submit" type="submit" class="btn w-100 btn-dark" value="Submit">
                <br>
            </form>
          </div>
      </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <!-- <pingendo onclick="window.open('https://pingendo.com/', '_blank')" style="cursor:pointer;position: fixed;bottom: 10px;right:10px;padding:4px;background-color: #00b0eb;border-radius: 8px; width:250px;display:flex;flex-direction:row;align-items:center;justify-content:center;font-size:14px;color:white">Made with Pingendo Free&nbsp;&nbsp;
    <img src="https://pingendo.com/site-assets/Pingendo_logo_big.png" class="d-block" alt="Pingendo logo" height="16">
  </pingendo> -->
</body>

</html>

percobaan/templates/percobaan/lpsb.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static 'css/theme.css' %}" type="text/css"> </head>

<body class="">
  <div class="m-0 py-4 bg-primary">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="text-center">LIST PENDAFTAR</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <table class="table">
            <thead>
              <tr>
                <th class="text-left">No Urut Pendaftar</th>
                <th>Nama</th>
                <th>NPM</th>
                <th>Waktu Daftar</th>
                <th>Status Terima</th>
                <th>Pilih</th>
              </tr>
            </thead>
            <tbody>
              {% for row in tabel_pendaftaran %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ row.1 }}</td>
                  <td>{{ row.2 }}</td>
                  <td>{{ row.3 }}</td>
                  <td>{{ row.4 }}</td>
                  <td>
                      <a class="btn btn-success" href="#" contenteditable="true">Terima</a>
                      <a class="btn btn-danger" href="#">Tolak</a>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <!-- <pingendo onclick="window.open('https://pingendo.com/', '_blank')" style="cursor:pointer;position: fixed;bottom: 10px;right:10px;padding:4px;background-color: #00b0eb;border-radius: 8px; width:250px;display:flex;flex-direction:row;align-items:center;justify-content:center;font-size:14px;color:white">Made with Pingendo Free&nbsp;&nbsp;
    <img src="https://pingendo.com/site-assets/Pingendo_logo_big.png" class="d-block" alt="Pingendo logo" height="16">
  </pingendo> -->

  <script type="text/javascript" src="{% static 'js/jquery-latest.js' %}"></script> 
  <script type="text/javascript" src="{% static 'js/jquery.tablesorter.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery.tablesorter.min.js' %}"></script> 

<!-- Jquery script -->
<script>
   $(document).ready(function() 
      { 
        $("table").tablesorter(); 
      } 
    );
</script>
</body>

</html>

percobaan/templates/percobaan/lsb.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static 'css/theme.css' %}" type="text/css"> </head>

<body class="">
  <div class="m-0 py-4 bg-primary">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="text-center">LIST BEASISWA &nbsp;</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="table table-responsive">
        <table class="table table-hover" id="myTable" style="width: none;">
            <thead>
              <tr>
                  <th>No Urut Skema Beasiswa</th>
                  <th>Kode Skema</th>
                  <th>Waktu Penutupan</th>
                  <th>Status</th>
                  <th>Jumlah Pendaftar</th>
              </tr>
            </thead>
            <tbody>
              {% for row in tabel_skema %}
              
                <tr>
                  <td>{{ row.0 }}</td>
                  <td><a href="{% url 'percobaan:open_pendaftar' row.0 row.1 %}">{{ row.1 }}</a></td>
                  <td>{{ row.2 }}</td>
                  <td>{{ row.3 }}</td>
                  <td>{{ row.4 }}</td>
                </tr>
              
              {% endfor %}
            </tbody>
        </table>
      </div>
    </div>  
  </div>
  
  
  <!-- Jquery n Bootstrap Script -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

  <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <!-- <pingendo onclick="window.open('https://pingendo.com/', '_blank')" style="cursor:pointer;position: fixed;bottom: 10px;right:10px;padding:4px;background-color: #00b0eb;border-radius: 8px; width:250px;display:flex;flex-direction:row;align-items:center;justify-content:center;font-size:14px;color:white">Made with Pingendo Free&nbsp;&nbsp;
    <img src="https://pingendo.com/site-assets/Pingendo_logo_big.png" class="d-block" alt="Pingendo logo" height="16">
  </pingendo> -->
  <script type="text/javascript" src="{% static 'js/jquery-latest.js' %}"></script> 
  <script type="text/javascript" src="{% static 'js/jquery.tablesorter.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery.tablesorter.min.js' %}"></script> 

<!-- Jquery script -->
<script>
   $(document).ready(function() 
      { 
        $("table").tablesorter(); 
      } 
    );
</script>
</body>

</html>